#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# vim: set ft=python ts=3 sw=3 expandtab:
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#              C E D A R
#          S O L U T I O N S       "Software done right."
#           S O F T W A R E
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Author   : Kenneth J. Pronovici <pronovic@ieee.org>
# Language : Python (>= 2.3)
# Project  : Cedar Backup, release 2
# Revision : $Id$
# Purpose  : Implements Cedar Backup cback script.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

"""
Implements Cedar Backup cback script.
@author: Kenneth J. Pronovici <pronovic@ieee.org>
"""

# Check the Python version.  We require 2.3 or greater.
try:
   if map(int, [sys.version_info[0], sys.version_info[1]]) < [2, 3]:
      print "Python version 2.3 or greater required, sorry."
      sys.exit(1)
except:
   # sys.version_info isn't available before 2.0
   print "Python version 2.3 or greater required, sorry."
   sys.exit(1)

from CedarBackup2.cli import cli
cli()

