#!/bin/ksh
# Sensibly creates a branch off a named release in Subversion.

if [[ $# != 1 || ${1} == "--help" ]]
then
   print "Usage: branch <version> <branchname>"
   exit 1
fi

VERSION=${1}
BRANCH=${2}

svn copy svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/tags/CEDAR_BACKUP2_V${VERSION} \
         svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/branches/${BRANCH} \
         -m "Branching version ${VERSION} to branch ${BRANCH}."
if [[ $? != 0 ]]
then
   print "Failed to create branch ${BRANCH}."
   exit 1
fi

print "Completed branching version ${VERSION} to branch ${BRANCH}:"
print ""

svn list --verbose svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/branches

print ""

