#!/bin/ksh
# Sensibly creates a release label in Subversion.

if [[ $# != 1 || ${1} == "--help" ]]
then
   print "Usage: release <version>"
   exit 1
fi

VERSION=${1}

svn copy svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/trunk \
         svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/tags/CEDAR_BACKUP_V${VERSION} \
         -m "Tagging the ${VERSION}} release of Cedar Backup."

print "Completed tagging release ${VERSION} of Cedar Backup:"
print ""

svn list --verbose svn+ssh://daystrom/opt/public/svn/software/cedar-backup2/tags

print ""
print "Make sure to re-run this script if you forgot to update"
print "the Changelog or CedarBackup2/release.py!"
print ""

