#!/bin/ksh
# Runs the validating nsgmls processor against the indicated XML file.
SOC="/usr/share/xml/declaration/xml.soc"
DECL="/usr/share/xml/declaration/xml.dcl"
SP_CHARSET_FIXED=YES SP_ENCODING=XML nsgmls -wxml -m${SOC} -ges ${DECL} $*
